//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_Practice.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Collection_OrdersTeas
    {
        public int ID_CollectionOrderTea { get; set; }
        public int Order_ID { get; set; }
        public int Collection_ID { get; set; }
        public int CollectionOrderTea_Count { get; set; }
    
        public virtual Collections Collections { get; set; }
        public virtual Orders Orders { get; set; }
    }
}
