//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_Practice.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CollectionsMenu
    {
        public int ID { get; set; }
        public string Image_Url { get; set; }
        public string Collection_Name { get; set; }
        public string Collection_Description { get; set; }
        public string At_Storage { get; set; }
        public int Stored_Count { get; set; }
    }
}
