//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_Practice.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pack_OrdersTeas
    {
        public int ID_PackOrderTeas { get; set; }
        public int TeaSort_ID { get; set; }
        public int Package_ID { get; set; }
        public int Order_ID { get; set; }
        public int PackOrderTeas_Count { get; set; }
    
        public virtual Orders Orders { get; set; }
        public virtual Packages Packages { get; set; }
        public virtual TeaSorts TeaSorts { get; set; }
    }
}
