//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_Practice.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Storage
    {
        public int ID_Storage { get; set; }
        public int Tea_ID { get; set; }
        public int Storage_CountTea { get; set; }
    
        public virtual TeaSorts TeaSorts { get; set; }
    }
}
