//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_Practice.database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TeaShopDBContext : DbContext
    {
        public TeaShopDBContext()
            : base("name=TeaShopDBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Accounts> Accounts { get; set; }
        public virtual DbSet<Collection_OrdersTeas> Collection_OrdersTeas { get; set; }
        public virtual DbSet<CollectionForms> CollectionForms { get; set; }
        public virtual DbSet<Collections> Collections { get; set; }
        public virtual DbSet<CollectionsStorage> CollectionsStorage { get; set; }
        public virtual DbSet<CollectionTeas> CollectionTeas { get; set; }
        public virtual DbSet<Cup_OrdersTeas> Cup_OrdersTeas { get; set; }
        public virtual DbSet<Cups> Cups { get; set; }
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<Pack_OrdersTeas> Pack_OrdersTeas { get; set; }
        public virtual DbSet<Packages> Packages { get; set; }
        public virtual DbSet<Producers> Producers { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Storage> Storage { get; set; }
        public virtual DbSet<TeaSorts> TeaSorts { get; set; }
        public virtual DbSet<TeaTypes> TeaTypes { get; set; }
        public virtual DbSet<CollectionsMenu> CollectionsMenu { get; set; }
        public virtual DbSet<TeasMenu> TeasMenu { get; set; }
    }
}
