//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_Practice.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeaSorts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TeaSorts()
        {
            this.CollectionTeas = new HashSet<CollectionTeas>();
            this.Cup_OrdersTeas = new HashSet<Cup_OrdersTeas>();
            this.Pack_OrdersTeas = new HashSet<Pack_OrdersTeas>();
            this.Storage = new HashSet<Storage>();
        }
    
        public int ID_TeaSort { get; set; }
        public int TeaType_ID { get; set; }
        public Nullable<int> Producer_ID { get; set; }
        public string TeaSort_Name { get; set; }
        public string TeaSort_Description { get; set; }
        public decimal TeaSort_FermentatinPeriod { get; set; }
        public decimal TeaSort_PackPrice { get; set; }
        public decimal TeaSort_CupPrice { get; set; }
        public string TeaSort_ImageUrl { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CollectionTeas> CollectionTeas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cup_OrdersTeas> Cup_OrdersTeas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pack_OrdersTeas> Pack_OrdersTeas { get; set; }
        public virtual Producers Producers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Storage> Storage { get; set; }
        public virtual TeaTypes TeaTypes { get; set; }
    }
}
